### ISSUE TITLE
admin can see some data

### ISSUE THREAD

**Issue by ivanromakh** [Scholar-6/brillder#4713]

**Comment by ivanromakh** [comment]
![image](https://user-images.githubusercontent.com/18567511/192814437-5b5c701c-278d-4bc7-a8a4-5115bbe05bf9.png)

**Comment by s-steddy** [comment]
Some comments now this is largely in place:

The way subject selection works needs fine tuning. For one, the text in the dropdown box needs correcting - if you select a category or several subjects they get stringed together and the font goes wrong:
<img width="267" alt="image" src="https://user-images.githubusercontent.com/107257153/200611182-b968db3a-9095-4108-af9a-1f2fe7ac633a.png">

It would make more sense for me to have something like this:
![2022-11-08 15 51 56](https://user-images.githubusercontent.com/107257153/200615942-63e72d7a-a915-419a-8d45-5095fb7795da.jpg)

Have **categories** in the drop-down, along with the 'Everything' option. 
Have subjects beneath, scrollable, with checkboxes. Subjects are sorted A->Z, but with subjects with bricks first. 

Selecting a category from the dropdown selects (ie. fills the checkbox) the related subjects, e.g. choosing 'Languages' from the dropdown would select French, Spanish, Eng Lang etc in the subjects list. User can of course check or uncheck subjects in this list as they go.

**Comment by s-steddy** [comment]
The sort buttons on columns don't work as indicated. 

For one, they only sort one way, so either enable sorting in the other direction (useful for dates), or the icon should be a single down arrow, not an up-and-down arrow. 
The sort-by-date-published option doesn't seem to be working right, not sure what's caused this:
<img width="93" alt="image" src="https://user-images.githubusercontent.com/107257153/200617852-3ebe412f-1584-4c5d-b8a1-1ae28a329fcc.png">
Sorting by visibility (or better, filtering) is probably a good idea.

**Comment by s-steddy** [comment]
I'm not sure if this is a current connection issue, but the search bar doesn't seem to be working. Here I'm searching for Peres - you can see Toby's brick in the list. Same if I try with a title

<img width="800" alt="image" src="https://user-images.githubusercontent.com/107257153/200618719-83f3f2dd-d45c-4779-ac58-48a64d998898.png">

**Comment by s-steddy** [comment]
The export function is working pretty well, but add a timestamp to the filename to avoid the risk of downloads being overwritten

<img width="500" alt="image" src="https://user-images.githubusercontent.com/107257153/200619452-afa18841-9d1f-4708-9dc7-c56b72c5999b.png">

**Comment by s-steddy** [comment]
See #4748 for classes panel

**Comment by s-steddy** [comment]
Just a thought - do we want the brick title to be clickable, and to direct to the brick? And would it be easy to navigate back from there?

**Comment by s-steddy** [comment]
From Joe: Add a sponsor field

**Comment by ivanromakh** [comment]
@s-steddy sponsor field added. As I remember only text

**Comment by ivanromakh** [comment]
sort by date should work now. using date created when date published is empty.

**Comment by s-steddy** [comment]
Update on 23rd Nov:

The subject selection sidebar is better, but still not working perfectly. It should be more like the category selection sidebar in the catalogue, really. So:

**Instead of** plain alphabetical list:
<img width="200" alt="image" src="https://user-images.githubusercontent.com/107257153/203540726-70042eff-e578-4f45-862a-9145e4282899.png">

- [ ] The list should have at the top, like this, just the subjects for which we have bricks **but in alphabetical order** (but no need for numbers):
<img width="200" alt="image" src="https://user-images.githubusercontent.com/107257153/203541124-78b608e1-d6a0-4a63-88cb-618d796839ec.png">

- [ ] When a subject is 'checked' (ie. selected), base the design on the catalogue page again, ie. an outlined circle in the subject colour, like this. So, **not this**:

<img width="150" alt="image" src="https://user-images.githubusercontent.com/107257153/203542559-05c3e75d-9602-459f-9a74-de89fa22f298.png">

But for this, _unlike_ in catalogue (which will need work some time) have the line highlight to light blue, not white, and don't move to top of list:
<img width="150" alt="image" src="https://user-images.githubusercontent.com/107257153/203542347-e1f665cd-1a31-4ad3-b998-0314885f23e4.png">

The dropdown category selection seems to be loading the right bricks in the window, but in the sidebar the right thing doesn't happen. The only dropdown option that seems to select the right subjects is Art and Design. Here, I've selected science, so it has loaded science bricks in the window, but the sidebar hasn't selected chemistry, for example:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/107257153/203543248-50084e58-0ef4-446c-a3b1-569558768914.png">

- [ ] Make sure the other categories select the right subjects, grouped like the subject dashboard. Selecting from the dropdown clears any current selections. Eg, if I was looking at French, then selected Science in the dropdown, only science subjects should become selected, not French+science.

- [ ] There looks to be a bug that when you select 'all' from the dropdown after selecting some subjects, it makes General and Topical be selected.

**Comment by s-steddy** [comment]
- [ ] Fields that are sortable need to be sortable in both directions. This includes Published, Author, and Played.
- [ ] Author and visibility will work best as filters, like subject. We will likely need a new design, or at least to think how this works.

**Comment by s-steddy** [comment]
- [ ] Export file needs to have timestamp as well as date, as customers are likely to download more than one set of data on the same day.

**Comment by ivanromakh** [comment]
@s-steddy it is going to be: Brillder data 25.11.22 12_32.xlsx

**Comment by ivanromakh** [comment]
@s-steddy All bricks will not load in browser. it will lead to memory leak.

**Comment by s-steddy** [comment]
Much improved, but I think the sorting of subjects in the sidebar still isn't quite right. This is what I get when I arrive at the page:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/107257153/205086956-df6a5438-5aa9-48ef-853a-c2ff3b3ac117.png">

It looks like the subjects in the sidebar are sorted by most bricks or most bricks played, currently it goes from Maths to Sociology, after which it lists the rest of the subjects for which there are no played bricks in alphabetical order. But what I see when I arrive should be alphabetical. Can we just hide the subjects for which there are no bricks played within the selected timeframe?

The sidebar also doesn't change if you select a category group from the dropdown, so, eg. if I select languages I wouldn't expect to see maths at the top of the list:

<img width="250" alt="image" src="https://user-images.githubusercontent.com/107257153/205090317-67aacb8e-66a1-4192-aa0a-6c67e47a3665.png">

How about hiding subjects here too which are not within subject category if you select from the dropdown?

**Comment by s-steddy** [comment]
Suggestions from Joe 30th Nov:

Class Name is underlined and clickable - when you click you go to the list of bricks been set to the class.

Teacher Name is underlined and clickable - when you click it goes to a version of "manage classes" for that teacher - not "My Classes" but "Joe Francis's Classes". Needs design as part of work on Assignments 

- [ ] Class icon is clickable - students in a circle
    - grey when no students have accepted or when classes without students are created
    - dark blue students in white circle from the moment when 1 student accepts the invitation (e.g. 1/12)
    - white students in dark blue circle from the moment where 2/3rds of students have responded

- [ ] Bricks no longer needs an icon, just a number (and not clickable)

- [ ] Activity has a clickable icon. The activity is the total play attempts of bricks of students in the class. It's a number. The Activity icon is books on a circle.
    - grey when no students have played or no bricks been set.
    - dark blue books in white circle from the moment when 1 student plays a brick.
    - white books in dark blue circle from the moment when 2/3rds of bricks set have been played by at least one student.

**Comment by s-steddy** [comment]
Closing this issue now. Future work can be logged separately.
